### ISSUE TITLE
ci: add workflow to auto deploy typedoc to github pages

### ISSUE THREAD

**Issue by aayushchugh** [aayushchugh/maya#25]
create a new file `.github/workflows/deploy-docs.yml` and paste the following contents

```yml
name: Build and Deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:
permissions:
    contents: write
jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                  yarn install
                  yarn docs

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs # The folder the action should deploy.
```
